### PR TITLE
Fix data device errors in SAM_generators

### PR DESCRIPTION
**Pull request by aldro61**
Hi Diviyan,

I encountered a device error when running the SAM code. Here's a simple fix.

Cheers,
Alex

### CODE REVIEW

**Comment by Diviyan-Kalainathan** [comment]
Hi Alex, 
Thanks for the feedback, however, I don't see why you had an issue there: the line L291: 
```
sam = sam.to(device)
```
should do the trick: it send all registered buffers on the GPU devices.

Best,
Diviyan

**Comment by aldro61** [comment]
I was also expecting the behaviour you mention. However I was getting some device errors in this class, which were solved by explicitly sending the tensors to the GPU. It seemed like the tensors were not getting pushed to the GPU, even after a call to sam.to(...).

It might due to my setup. I’ll investigate more and let you know. Feel free to close the PR in the mean time.

Thanks,
Alex

**Comment by Diviyan-Kalainathan** [comment]
Ok noted, don't hesitate to reopen it if you have more info on the issue ! 

Best, 
Diviyan

**Comment by Diviyan-Kalainathan** [comment]
I also noticed this bug, I will apply the fix.

**Pull request closed without merging**
